name: Deploy API
on:
  push:
    branches:
      - staging
env:
  ENVIRONMENT_NAME: stage
jobs:
  qa:
    name: Deploy API Staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    container: ghcr.io/matrjones/deploy-aws:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::060795902215:role/pipeline-role
          aws-region: eu-west-1

      - name: Set execute permissions
        run: |
          chmod +x ./backend/scripts/api/plan.sh
          chmod +x ./backend/scripts/api/apply.sh
          chmod +x ./backend/scripts/api/build.sh

      - name: Install .NET SDK (Alpine)
        run: |
          apk add --no-cache \
              bash \
              curl \
              dotnet8-sdk

          dotnet --version

      - name: Build API
        run: ./backend/scripts/api/build.sh stage

      - name: Plan API
        run: ./backend/scripts/api/plan.sh stage

      - name: Apply API
        run: ./backend/scripts/api/apply.sh stage
