name: Deploy API
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT_NAME:
        description: "Environment Name"
        required: true
        default: "stage"

env:
  ENVIRONMENT_NAME: stage
jobs:
  qa:
    name: Deploy API Staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    container: ghcr.io/matrjones/deploy-aws:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::060795902215:role/pipeline-role
          aws-region: eu-west-1

      - name: Set execute permissions
        run: |
          chmod +x ./backend/scripts/api/refresh.sh

      - name: Refresh Terraform
        run: ./backend/scripts/api/refresh.sh stage
